blank_issues_enabled: false
contact_links:
  - name: Feedback
    url: https://github.com/ju4n97/lector/discussions
    about: Please suggest ideas for Lector here.
    
  - name: Question about Lector
    url: https://github.com/ju4n97/lector/discussions
    about: Please ask and answer questions here.