blank_issues_enabled: true
contact_links:
  - name: Feedback
    url: https://github.com/lectorjs/lector/discussions/categories/ideas
    about: Please suggest ideas for Lector here.

  - name: Question about Lector
    url: https://github.com/lectorjs/lector/discussions/categories/q-a
    about: Please ask and answer questions here.
