blank_issues_enabled: true
contact_links:
  - name: Feedback
    url: https://github.com/ju4n97/librereader/discussions/categories/ideas
    about: Please suggest ideas for LibreReader here.

  - name: Question about LibreReader
    url: https://github.com/ju4n97/librereader/discussions/categories/q-a
    about: Please ask and answer questions here.
