name: release

on:
  push:
    branches: [master]      

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create a Github release
      id-token: write # To publish on JSR
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create release pull-request
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run ci:version
          publish: bun run ci:release
          title: "ci: release 📦"
          commit: "ci: release 📦"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: https://github.com/changesets/changesets/issues/1318
      - name: Publish to JSR
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: bunx jsr publish
